#ifndef CONFIG_H
#define CONFIG_H

/* MySensors configuration */
#define MY_DEBUG
#define MY_REPEATER_FEATURE
#define MY_RADIO_RF24
#define MY_RF24_CE_PIN 9
#define MY_RF24_CS_PIN 10
#define MY_RF24_PA_LEVEL RF24_PA_MAX

/*  */
#define CONFIG_PERIPH_LED_RED_PIN 7
#define CONFIG_PERIPH_LED_YELLOW_PIN 6
#define CONFIG_PERIPH_LED_GREEN_PIN 5
#define CONFIG_PERIPH_HEATER_TRIAC_N_PIN 4
#define CONFIG_PERIPH_HEATER_TRIAC_P_PIN 3

#endif
